---

- name: User to execute the manage docker on behalf of monitoring
  # This can have security issues when docker manages other containers too
  become: yes
  user:
    name: "{{ monitoring_user_name }}"
    state: present
    shell: /bin/bash
    home: "{{ monitoring_user_home_dir }}"

- name: Install docker
  include_role: geerlingguy.docker
  vars:
    docker_users:
      - "{{ monitoring_user_name }}"

- name: Working directory
  file:
    state: dir
    path: "{{ monitoring_working_dir }}"

- name: Render template for the docker-compose file.
  template:
    src: monitoring-docker-compose.yml.j2
    dest: "{{ monitoring_working_dir }}/docker-compose.yml"

- name: Bring up the containers
  command: "docker-compose up"
  chdir: "{{ monitoring_working_dir }}"
