---
- name: Copy the installer script
  copy:
    dest: "{{ monitoring_working_dir }}/ssh-users.sh"
    src:  "files/ssh-users.sh"
    mode:  0744
    owner: "{{ monitoring_user_name }}"

- name: Run the installer script
  command: "{{ monitoring_working_dir }}/ssh-users.sh"
  become: true
  become_user: "{{ monitoring_user_name }}"
  args:
    chdir: "{{ monitoring_working_dir }}"
  changed_when: false

- name: Render the daemon
  template:
    src: prometheus-active-users.service.j2
    dest: /etc/systemd/system/prometheus-active-users.service
    owner: root
    group: root
    mode: 0644

- name: Reload systemd
  systemd:
    daemon_reload: yes
